services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5432:5432
    volumes:
        - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
        - 27017:27017
    volumes:
        - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  auction-svc:
    image: trycatchlearn/auction-svc:latest  
    build:
        context: .
        dockerfile: src/AuctionService/Dockerfile
    environment:
        - ASPNETCORE_ENVIORMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__Default=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Auctions;
        - IdentityServiceUrl=http://identity-svc
    ports:
        - 5004:80
    depends_on:
        - postgres
        - rabbitmq
  search-svc:
    image: trycatchlearn/search-svc:latest
    build:
        context: .
        dockerfile: src/SearchService/Dockerfile
    environment:
        - ASPNETCORE_ENVIORMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__MongoDb=mongodb://root:mongopw@mongodb
        - AuctionServiceUrl=http://auction-svc
    ports:
        - 5005:80
    depends_on:
        - mongodb
        - rabbitmq
  identity-svc:
    image: trycatchlearn/identity-svc:latest
    build:
        context: .
        dockerfile: src/IdentityService/Dockerfile
    environment:
        - ASPNETCORE_ENVIORMENT=Docker
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Identity;
    ports:
        - 5000:80
    depends_on:
        - postgres
  gateway-svc:
    image: trycatchlearn/gateway-svc:latest
    build:
        context: .
        dockerfile: src/GatewayService/Dockerfile
    environment:
        - ASPNETCORE_ENVIORMENT=Docker
        - ASPNETCORE_URLS=http://+80
    ports:
        - 6001:80